name: Create UPM branches and run NPM publish

on:
  push:
    tags:
      - v*

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get tag name
        id: tag
        run: echo ::set-output name=name::${GITHUB_REF#refs/tags/v}

      - name: Create UPM branch
        uses: hecomi/create-upm-branch-action@main
        with:
          git-tag: ${{steps.tag.outputs.name}}
          pkg-root-dir-path: Assets/EventChannelUnit
          main-branch: main

      - name: Tag UPM branch
        run: |
          git tag upm/${{steps.tag.outputs.name}} \
          git push origin upm/${{steps.tag.outputs.name}}
          
